- url: https://clouddocs.f5.com/api/irules/Operators.html
  max_depth: 1
  ttl_days: 90
- url: https://clouddocs.f5.com/api/irules/Events.html
  max_depth: 1
  ttl_days: 90
- url: https://clouddocs.f5.com/api/irules/Commands.html
  max_depth: 1
  ttl_days: 90
- url: https://clouddocs.f5.com/cli/tmsh-reference/latest/general/
  max_depth: 2
  ttl_days: 90
- url: https://clouddocs.f5.com/cli/tmsh-reference/latest/commands/
  max_depth: 2
  ttl_days: 90
- url: https://clouddocs.f5.com/cli/tmsh-reference/latest/modules/
  max_depth: 2
  ttl_days: 90
#- url: https://my.f5.com/manage/s/article/K73819494
#  max_depth: 3
#  ttl_days: 90
#- url: https://my.f5.com/manage/s/article/K70671013
#  max_depth: 2
#  ttl_days: 90
#- url: https://my.f5.com/manage/s/article/K38201755
#  max_depth: 2
#  ttl_days: 90
#- url: https://my.f5.com/manage/s/article/K20775035
#  max_depth: 2
#  ttl_days: 90
#- url: https://my.f5.com/manage/s/article/K85426947
#  max_depth: 2
#  ttl_days: 90
#- url: https://my.f5.com/manage/s/article/K05939436
#  max_depth: 2
#  ttl_days: 90

#  ttl_days: 90
#- url: https://clouddocs.f5.com/api/velos-api/F5OS-C-1.8.1-cli.html
#  max_depth: 1
#  ttl_days: 90
#- url: https://clouddocs.f5.com/api/rseries-api/F5OS-A-1.8.0-cli.html#r2r4
#  max_depth: 1
#  ttl_days: 90
#- url: https://clouddocs.f5.com/api/rseries-api/F5OS-A-1.8.0-cli.html#r5r10
#  max_depth: 1
#  ttl_days: 90
#
#
